INSERT INTO CLIENTS(NAME , LAST_NAME, AGE ,GENDER ) VALUES ('alejandro','munoz','23','Man');
INSERT INTO CLIENTS(NAME , LAST_NAME, AGE ,GENDER )  VALUES ('karla','gustaf','23','Man');
INSERT INTO CLIENTS(NAME , LAST_NAME, AGE ,GENDER ) VALUES ('rosa','melano','23','Man');
INSERT INTO CLIENTS(NAME , LAST_NAME, AGE ,GENDER )  VALUES ('maria','jeje','23','Man');
INSERT INTO CLIENTS(NAME , LAST_NAME, AGE ,GENDER ) VALUES ('luis','munguia','23','Man');
INSERT INTO CLIENTS(NAME , LAST_NAME, AGE ,GENDER ) VALUES ('ana','laura','23','Man');
INSERT INTO CLIENTS(NAME , LAST_NAME, AGE ,GENDER )  VALUES ('jessica','mami','23','Man');
INSERT INTO CLIENTS(NAME , LAST_NAME, AGE ,GENDER ) VALUES ('sowie','rata','23','Man');
INSERT INTO CLIENTS(NAME , LAST_NAME, AGE ,GENDER )  VALUES ('ivan','lemon','23','Man');
INSERT INTO CLIENTS(NAME , LAST_NAME, AGE ,GENDER )  VALUES ('carlos','joqita','23','Man');
INSERT INTO CLIENTS(NAME , LAST_NAME, AGE ,GENDER )  VALUES ('maribale','guardia','23','Man');

INSERT INTO PRODUCTS (NAME, PRICE, CREATE_AT) VALUES('Panasonic Pantalla LCD', 259990, NOW());
INSERT INTO PRODUCTS (NAME, PRICE, CREATE_AT)VALUES('Sony Camara digital DSC-W320B', 123490, NOW());
INSERT INTO PRODUCTS (NAME, PRICE, CREATE_AT) VALUES('Apple iPod shuffle', 1499990, NOW());
INSERT INTO PRODUCTS (NAME, PRICE, CREATE_AT) VALUES('Sony Notebook Z110', 37990, NOW());
INSERT INTO PRODUCTS (NAME, PRICE, CREATE_AT) VALUES('Hewlett Packard Multifuncional F2280', 69990, NOW());
INSERT INTO PRODUCTS (NAME, PRICE, CREATE_AT) VALUES('Bianchi Bicicleta Aro 26', 69990, NOW());
INSERT INTO PRODUCTS (NAME, PRICE, CREATE_AT) VALUES('Mica Comoda 5 Cajones', 299990, NOW());

INSERT INTO ADDRESS (STREET, CITY, STATE,ZIP) VALUES('Vista Hermosa','Jose santos chocano','colima','578');
INSERT INTO ADDRESS (STREET, CITY, STATE,ZIP)VALUES('Vista Hermosa','Jose santos chocano','colima','578');
INSERT INTO ADDRESS (STREET, CITY, STATE,ZIP) VALUES('Vista Hermosa','Jose santos chocano','colima','578');
